src/WebUI/WebUI/Models/MusicItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class MusicItem
    {
        public string Id { get; set; }
        public string Title { get; set; }
    }
}

src/WebUI/WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            var files = new List<MusicItem>();
            files.Add(new MusicItem() {Id = Guid.NewGuid().ToString(), Title = "Dummy track"});
            return View(files);
        }

    }
}

src/WebUI/WebUI/Controllers/StreamController.cs
using System;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class StreamController : Controller
    {
        public ActionResult PlaySingleTrack(Guid id)
        {
            return new RedirectResult(string.Format("http://localhost:50231/api/stream/{0}", id));
        }
    }
}

src/WebUI/WebUI/Views/Home/Index.cshtml
@model IEnumerable<WebUI.Models.MusicItem>
@{
    ViewBag.Title = "Media Player";
}

<div id="header">Top section</div>
<div id="sidebar">
    <div id="player">
        <a href="#" class="button" id="PreviousTrack" title="Previous Track">Previous</a>
        <a href="#" class="button" id="PlayTrack" title="Play/Pause">Play</a>
        <a href="#" class="button" id="PauseTrack" title="Play/Pause" style="display: none;">Pause</a>
        <a href="#" class="button" id="NextTrack" title="Next Track">Next</a>
        <div>
            <div id="playdeck"></div>
        </div>       
        <div><a href="#" class="button" id="action_ToggleSideBar" title="Toggle Side Bar"></a></div>
            <div id="playermiddle">
                <div id="audiocontainer">
                    <div class="audiojs" id="audio_wrapper0">
                    <div class="scrubber"><div class="progress"></div><div class="loaded"></div></div>
                    <div class="time"><em id="played">00:00</em>/<strong id="duration">00:00</strong></div>
                    <div class="error-message"></div>
                    </div>
                </div>
                <div id="preview"></div>
            </div>
    </div>
    <div id="nowPlaying">
        <table>
            <tr>
                <th>Title</th>
            </tr>
            <tbody>
                @foreach (var item in Model.Take(10))
                {
                    <tr><td><a href="#" class="button" onclick="playUrl('@Guid.NewGuid()')">@item.Title</a></td></tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div id ="libraryContainer">
    <table>
    <tr>
        <th>Title</th>
    </tr>
    <tbody>
    @foreach (var item in Model)
    {
        <tr><td><span>@Html.ActionLink(item.Title, "PlaySingleTrack", "Stream", new { id = item.Id }, null)</span></td></tr>
    }
    </tbody>
    </table>
</div>
<script type="text/javascript">
    function playUrl(itemId) {
        $("#playdeck").jPlayer("destroy");
        var url = 'http://localhost:3579/Stream/PlaySingleTrack/' + itemId;
        $("#playdeck").jPlayer({
            ready: function() {
                $(this).jPlayer("setMedia", {
                    mp3: url
                });
                $(this).jPlayer("play");
            },
            supplied: "mp3",
            swfPath: "/Scripts",
            cssSelectorAncestor: "#player",
            cssSelector: {
                play: "#PlayTrack",
                pause: "#PauseTrack",
                seekBar: "#audiocontainer .scrubber",
                playBar: "#audiocontainer .progress",
                currentTime: "#played",
                duration: "#duration"
            },
        });
        $.jPlayer.timeFormat.showHour = true;
    }
  </script>

src/WebUI/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
      
</head>
<body>
    <div id="jquery_jplayer_1"></div>
    @RenderBody()
</body>
</html>